version: "3.10"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend:latest
    ports:
      - 8081:8081
    networks:
      - project_network
networks:
  project_network:
